name: ci

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.x

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          headless: true
          record: false
          browser: chrome
          start: yarn dev
          wait-on: 'http://localhost:3000'
